name: khedni_maak
description: University project 2020 C2

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #  login dependency
  # flutter_login: ^1.0.14
  #  used for login
  transformer_page_view: ^0.1.6
  flushbar: ^1.10.4
  #  introduction screen dependency
  introduction_screen: ^1.0.9
  #  dependency user for map
  #  google_maps_flutter: ^0.5.30
  google_maps_flutter: ^1.0.3
  #  geolocator: ^6.0.0+4
  geolocator: ^6.0.0+4
  permission_handler: ^5.0.1+1
  google_maps_webservice: ^0.0.18
  tuple: ^1.0.3
  flutter_polyline_points: ^0.2.4
  #  http requests dependency
  http: ^0.12.2
  #firebase_core
  firebase_core: ^0.5.0+1
  #firestore cloud
  cloud_firestore: ^0.14.1+3
  firebase_messaging: ^7.0.3
  #  fonts dependency
  font_awesome_flutter: ^8.10.0
  intl: ^0.16.1
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  outline_material_icons: ^0.1.1
  # dummy package to test https://github.com/NearHuscarl/flutter_login/issues/35
  provider: ^4.3.2+2
  url_launcher: ^5.7.8
  # icons
  fleva_icons: ^1.0.2
  #date time picker
  datetime_picker_formfield: ^1.0.0
  #loading indicator
  flutter_spinkit: "^4.1.2"
  badges: ^1.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

